src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Auth::routes();

Route::get('/', 'HomeController@indexHome')->name('Welcome');
Route::get('/contacts', 'HomeController@indexContacts')->name('Contacts');
Route::get('/confNews', 'HomeController@indexNews')->name('ConfNews');
Route::get('/photos', 'HomeController@indexPhotos')->name('Photos');
Route::get('/comitet', 'HomeController@indexComitet')->name('Comitet');
Route::get('/archive', 'HomeController@indexArchive')->name('Archive');
Route::get('/requirements', 'HomeController@indexRequirements')->name('Requirements');
Route::get('/aboutconf', 'HomeController@indexConf')->name('aboutConf');
Route::get('/rasp', 'HomeController@indexRasp')->name('Rasp');


Route::group(['middleware' => 'is_Auth'], function(){
    Route::get('/lk/AboutMe', 'HomeController@AboutMe')->name('Info');
    Route::get('/lk/WorkStatus', 'HomeController@WorkStatus')->name('WorkStatus');
    Route::get('/lk/Diploms', 'HomeController@indexDiploms')->name('Diploms');
    Route::post('/lk/update/{id}', 'HomeController@UpdateMe')->name('UpdateMe');
    Route::post('/lk/answer/{id}', 'HomeController@sendAnswer')->name('SendAnswer');
    Route::post('/lk/editStatus/{id}', 'HomeController@editStatus')->name('editStatus');
    Route::post('/lk/makeDiplom', 'HomeController@makeDiplom')->name('makeDiplom');
    Route::get('/lk/getFile/{id}', 'DownloadController@getFile')->name('getFile');
    Route::get('/lk/getDiplom/{id}', 'DownloadController@getDiplom')->name('getDiplom');
    Route::get('lk/commentsComitet/{id}', 'HomeController@indexComitetComments')->name('indexComitetComments');
    Route::resource('/lk/comments', 'CommentsController');    
});

Route::group(['middleware' => 'is_Redactor'], function(){
    Route::resource('/news', 'NewController');
});

Route::get('/getPoloshenia', 'DownloadController@getOsnova')->name('getOsnova');
Route::get('/getPrimer', 'DownloadController@getPrimer')->name('getPrimer');

Route::resource('/works', 'WorkController');

src/resources/views/pages/articles.blade.php
s

src/resources/views/pages/comitet.blade.php
@extends('layouts.app1')

@section('title')
    Информация о комитете
@endsection

@section('content')

    <style>
        body {
            background-image: url(http://pictures.std-1056.ist.mospolytech.ru/blackfon.jpg)
        }

        .teacher {
            color: white
        }

    </style>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center"
                    style="margin-top: 100px; background-image: url(https://wallup.net/wp-content/uploads/2017/11/23/433673-minimalism-low_poly.jpg); border-radius: 20px">
                    Организационный комитет </h1>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="container mb-5" style="max-width: 1000px;">

        <div class="row mb-4">
            <div class="col-sm-4">
                <img class="shadow img-fluid"
                    src="http://pictures.std-1056.ist.mospolytech.ru/prepods/Muhanov.jpg"
                    alt="Описание изображения..." style="border: 5px solid #fff;">
                <p class="text-center teacher">Муханов Сергей Александрович</p>
                <p class="text-center teacher">к.п.н., доцент, доцент кафедры «Математика»,
                    руководитель секции №2;</p>
            </div>
            <div class="col-sm-4">
                <img class="shadow-sm img-fluid"
                    src="http://pictures.std-1056.ist.mospolytech.ru/prepods/Andreev.jpg"
                    alt="Описание изображения..." style="border: 5px solid #fff;">
                <p class="text-center teacher">Андреев Степан Николаевич</p>
                <p class="text-center teacher">д.ф.-м.н., зав. кафедрой «Математика» (председатель)</p>
            </div>
            <div class="col-sm-4">
                <img class="shadow-lg img-fluid"
                    src="http://pictures.std-1056.ist.mospolytech.ru/prepods/Bojkova.jpg"
                    alt="Описание изображения..." style="border: 5px solid #fff;">
                <p class="text-center teacher">Бойкова Галина Васильевна</p>
                <p class="text-center teacher">к.э.н., доцент, доцент кафедры «Математика»,
                    ответственный редактор Сборника трудов конференции</p>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-sm-4">
                <img class="shadow-sm img-fluid"
                    src="http://pictures.std-1056.ist.mospolytech.ru/prepods/Kogan.jpg"
                    alt="Описание изображения..." style="border: 5px solid #fff;">
                <p class="text-center teacher">Коган Ефим Александрович</p>
                <p class="text-center teacher">к.ф.-м.н., доцент, доцент кафедры «Математика»,
                    ответственный секретарь конференции</p>
            </div>
            <div class="col-sm-4">
                <img class="shadow-lg img-fluid"
                    src="http://pictures.std-1056.ist.mospolytech.ru/prepods/Samohin.jpg"
                    alt="Описание изображения..." style="border: 5px solid #fff;">
                <p class="text-center teacher">Самохин Вячеслав Николаевич</p>
                <p class="text-center teacher">д.ф.-м.н., профессор, профессор кафедры «Математика»,
                    руководитель секции №1</p>
            </div>
            <div class="col-sm-4">
                <img class="shadow img-fluid"
                    src="http://pictures.std-1056.ist.mospolytech.ru/prepods/Enikeev.jpg"
                    alt="Описание изображения..." style="border: 5px solid #fff;">
                <p class="text-center teacher">Еникеев Ильдар Хасанович</p>
                <p class="text-center teacher">д.т.н., профессор, профессор кафедры «Математика»,
                    руководитель секции №3</p>
            </div>
        </div>

    </div>

src/resources/views/pages/comments.blade.php
@extends('layouts.AppLK')

@section('title')
	Комментарии к работе
@endsection

@section('content')

<main class="page-content">
    <div class="container">
        @if (Session::has('message'))
            <div class = "alert alert-primary mt-3"> {{ Session::get('message') }} </div>
        @endif

		@include('common.errors')
    
        <div class="container content pl-0 pr-0">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if (Auth::user()->role != 'comitet')
                            <div class="card-header">Чат с представителем орг. комитета</div>
                        @else
                            <div class="card-header">Чат с участником конференции</div>
                        @endif
                        
                        <div class="card-body height3">
							@if (count($comments) > 0)
                            <ul class="chat-list">
                                @foreach ($comments as $comment)
                                    @if (Auth::user()->role != 'comitet')
                                        @if ($comment->user->role != 'comitet')  
                                            <li class="out">
                                                <div class="chat-img">
                                                    <img alt="Avtar" src="http://pictures.std-1056.ist.mospolytech.ru/user_semi_cobald.png">
                                                </div>
                                        @else
                                            <li class = "in">
                                                <div class="chat-img">
                                                    <img alt="Avtar" src="http://pictures.std-1056.ist.mospolytech.ru/politech_smart_logo.png">
                                                </div>
                                        @endif
                                            <div class="chat-body">
                                                <div class="chat-message">
                                                    <h5>{{ $comment->user->name }}</h5>
                                                    <h5><p>{{ $comment->text }}</p></h5>

                                                    <p class = "text-right">{{ date('d.m.Y H:i:s', strtotime("+3 hours", strtotime($comment->created_at))) }}</p>
                                                </div>
                                            </div>
                                        </li>
                                    @elseif (Auth::user()->role == 'comitet')
                                        @if ($comment->user->role != 'comitet')
                                            <li class="in">
                                                <div class="chat-img">
                                                    <img alt="Avtar" src="http://pictures.std-1056.ist.mospolytech.ru/user_semi_cobald.png">
                                                </div>
                                        @else
                                            <li class = "out">
                                                <div class="chat-img">
                                                    <img alt="Avtar" src="http://pictures.std-1056.ist.mospolytech.ru/politech_smart_logo.png">
                                                </div>
                                        @endif
                                            <div class="chat-body">
                                                <div class="chat-message">
                                                    <h5>{{ $comment->user->name }}</h5>
                                                    <h5><p>{{ $comment->text }}</p></h5>

                                                    <p class = "text-right">{{ date('d.m.Y H:i:s', strtotime("+3 hours", strtotime($comment->created_at))) }}</p>
                                                </div>
                                            </div>
                                        </li>
                                    @endif
                                @endforeach
                            </ul>
							@else
								Комментариев пока нет, но вы можете спросить нас!
							@endif
                        </div>
						
                        <div class = "row"> 
                            <div class = "col-12 mt-4">
                                @if (count($comments) > 0)
                                    <form action = "{{ route('SendAnswer', $ThisComment->id) }}" method = "POST">
                                        {{ csrf_field() }}
                                        <div class = "form-group">
                                            <input type = "hidden" value = "{{ Auth::user()->id }}" name = "user_id">
                        
                                            <div class = "row">
                                                <div class="col-10 pl-5 pr-0">
                                                    <textarea type="text" name="text" class="form-control" placeholder="Введите Ваше сообщение" style = "min-height: 70px"></textarea>
                                                </div>
                                                    
                                                <div class="col-2 pl-0">
                                                    <button type="submit" class = "form-control pl-0" style = "border: 0">
                                                        <i class="fab fa-telegram" style = "font-size: 55px; color: #17202b"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                @else
                                    <form action = "{{ route('comments.store') }}" method = "POST">
                                        {{ csrf_field() }}
                                        <div class = "form-group">
                                            <input type = "hidden" value = "{{ Auth::user()->id }}" name = "user_id">
                        
                                            <div class = "row">
                                                <div class="col-10 pl-5 pr-0">
                                                    <textarea type="text" name="text" class="form-control" placeholder="Введите Ваше сообщение" style = "min-height: 70px"></textarea>
                                                </div>
                                                    
                                                <div class="col-2 pl-0">
                                                    <button type="submit" class = "form-control pl-0" style = "border: 0">
                                                        <i class="fab fa-telegram" style = "font-size: 55px; color: #17202b"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                @endif
                            </div>
                        </div> 
                        <div class="card-footer text-muted text-center">
                            Московский Политех
                        </div>                       
                    </div>  
                </div>
            </div>
    </div>
</main>

<style>
    body{
        background-image: url(http://pictures.std-1056.ist.mospolytech.ru/whitefon.jpg)
    }

    .chat-list {
        padding: 0;
        font-size: .8rem;
    }

    .chat-list li {
        margin-bottom: 10px;
        overflow: auto;
        color: #ffffff;
    }

    .chat-list .chat-img {
        float: left;
        width: 48px;
    }

    .chat-list .chat-img img {
        -webkit-border-radius: 50px;
        -moz-border-radius: 50px;
        border-radius: 50px;
        width: 100%;
    }

    .chat-list .chat-message {
        -webkit-border-radius: 50px;
        -moz-border-radius: 50px;
        border-radius: 50px;
        background: rgba(135, 75,160);
        display: inline-block;
        padding: 10px 20px;
        position: relative;
    }

    .chat-list .chat-message:before {
        content: "";
        position: absolute;
        top: 15px;
        width: 0;
        height: 0;
    }

    .chat-list .chat-message h5 {
        margin: 0 0 5px 0;
        font-weight: 600;
        line-height: 100%;
        font-size: .9rem;
    }

    .chat-list .chat-message p {
        line-height: 18px;
        margin: 0;
        padding: 0;
    }

    .chat-list .chat-body {
        margin-left: 20px;
        float: left;
        width: 70%;
    }

    .chat-list .in .chat-message:before {
        left: -12px;
        border-bottom: 20px solid transparent;
        border-right: 20px solid rgba(135, 75,160);
    }

    .chat-list .out .chat-img {
        float: right;
    }

    .chat-list .out .chat-body {
        float: right;
        margin-right: 20px;
        text-align: right;
    }

    .chat-list .out .chat-message {
        background: #17202b;
    }

    .chat-list .out .chat-message:before {
        right: -12px;
        border-bottom: 20px solid transparent;
        border-left: 20px solid #17202b;
    }

    .card .card-header:first-child {
        -webkit-border-radius: 0.3rem 0.3rem 0 0;
        -moz-border-radius: 0.3rem 0.3rem 0 0;
        border-radius: 0.3rem 0.3rem 0 0;
    }
    .card .card-header {
        background: #17202b;
        border: 0;
        font-size: 1rem;
        padding: .65rem 1rem;
        position: relative;
        font-weight: 600;
        color: #ffffff;
    }

    .content{
        margin-top:40px;    
    }
</style>

@endsection

src/resources/views/pages/createNews.blade.php
@extends('layouts.app1')

@section('title')
	Создание новости
@endsection

@section('content')
	<div class = "container" style = "min-height: 700px; margin-top: 100px">
        <div class="card text-dark bg-light mt-5" style = "width: 75%; margin: 0 auto">
            @include('common.errors')
            
            <div class="card-header">
                <h3 class = "text-center"> Создание новости </h3>
            </div>

            <div class="card-body">

                <form action="{{ route('news.store') }}" method="POST" class="form-horizontal mt-3">
                    {{ csrf_field() }}

                    <div class = "row">
                        <div class = "col-12">
                            <b> Название: </b> 
        
                            <input type = "text" value="{{ old('label') }}" name = "label" class = "form-control">
                        </div>

                        <div class = "col-12 mt-2">
                            <b> Изображение: </b>
        
                            <input type = "text" value="{{ old('img') }}" name = "img" class = "form-control">
                        </div>
                    </div>

                    <div class = "row mt-2">
                        <div class = "col">
                            <b> Текст: </b> 
                            <textarea type = "text" name = "text" class = "form-control" style = "max-height: 100px; overflow-y: auto" placeholder="Ваш текст..."></textarea>
        
                            <button type = "submit" name = "Sub" class = "form-control mt-3 btn create">
                                <i class="fa fa-plus"></i> Создать 
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
	</div>
	
	<style>
		body{
            background-image: url(http://pictures.std-1056.ist.mospolytech.ru/blackfon.jpg)
        }

        h3{
            color: rgba(135, 75,160);
        }

        .create{
            background-color: rgba(135, 75,160);
            color: white;
        }
	</style>

@endsection

src/resources/views/pages/diploms.blade.php
@extends('layouts.AppLK')

@section('title')
	Дипломы и сертификаты
@endsection

@section('content')
<main class="page-content">
    <div class="container fon">
		@include('common.errors')
		
		@if (Session::has('message'))
			<div class = "alert alert-primary mt-3"> {{ Session::get('message') }} </div>
		@endif
		@if (Session::has('alert'))
			<div class = "alert alert-danger mt-3"> {{ Session::get('alert') }} </div>
		@endif
		
		<h3> Дипломы и сертификаты </h3>

		<hr>
		
		@if (Auth::user()->Diplom == '[]')
			<h5> Ваш сертификат ещё не создан :( </h5>
		@else
			<div class="row mt-3">
				<div class="col-6">
					<button class="btn btn download" type="submit" method="GET" onclick="location.href='{{ route('getDiplom', Auth::user()->id) }}'">Загрузить ваш сертификат</button>
				</div>
				<div class="col-6">
				</div>
			</div>
		@endif
    </div>
</main>

<style>
    body{
        background-image: url(http://pictures.std-1056.ist.mospolytech.ru/blackfon.jpg)
    }
	
	.fon{
		background-image: url(http://pictures.std-1056.ist.mospolytech.ru/whitefon.jpg);
		border-radius: 5px;
	}

	.download{
		background-color:  rgba(135, 75,160);
		color: white;
	}
</style>

@endsection

src/resources/views/pages/news.blade.php
@extends('layouts.app1')

@section('title')
	Новости
@endsection

@section('content')
	<div class="container-fluid mb-3">
		<div class="row">
			<div class = "col-12">
				<h1 class = "text-center" style="margin-top: 100px; background-image: url(https://wallup.net/wp-content/uploads/2017/11/23/433673-minimalism-low_poly.jpg); border-radius: 20px"> Новостная лента <span class="badge badge-dark badge-pill"> {{ count($news) }} </span> </h1>
			</div>
		</div>
	</div>
    
    <div class="container" style = "text-align: center; min-height: 650px">
        @if (Session::has('message'))
            <div class = "alert alert-primary mt-3"> {{ Session::get('message') }} </div>
        @endif

        @if (Auth::user() && Auth::user()->role == 'redactor')
            <a class = "btn btn create form-control mb-2" style = "font-size: 24px" href = "{{ route('news.create') }}"> Добавить новость </a>
        @endif

        @if (count($news) > 0)
            @foreach ($news as $currNews)
                <div class = "row myNews rounded-top" style = "margin-left: 0px; margin-right: 0px">
                    <div class = "col-6">
                        <h3 class = "text-left">{{ $currNews->label }}</h3>
                    </div>

                    <div class = "col-6" style = "text-align: right;">
                        @if (Auth::user() && Auth::user()->role == 'redactor')
                            <a class = "btn p-0">
                                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-pencil-square mr-2" fill="currentColor" xmlns="http://www.w3.org/2000/svg" onclick="location.href='{{route('news.edit', $currNews->id)}}'">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                                </svg>
                            </a>
                            
                            <form action = "{{ route('news.destroy', $currNews->id) }}" method = "POST" style = "display: inline">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                
                                <button type = "submit" class = "p-0">
                                    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style = "margin-right: 8px">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                    </svg>
                                </button>
                            </form>
                        @endif
                    </div>
                </div>

                <div class = "row myNews mb-3 rounded-bottom" style = "margin-left: 0px; margin-right: 0px">
                    <div class = "col-md-6 col-12">
                        <img style = "display: block; margin: auto" src = "{{ $currNews->img }}" width = "100%">
                    </div>
                        
                    <div class = "col-md-6 col-12">
                        <div style = "max-height: 230px; overflow-y: auto;">
                            <p class = "text-justify">{{ $currNews->text }}</p>
                        </div>

                        <hr>
                        <p class = "date text-right">{{ date('d.m.Y H:i:s', strtotime("+3 hours", strtotime($currNews->created_at))) }}</p>
                    </div>
                </div>
            @endforeach     
        @else
            Новостей нет
        @endif
    </div>
    
<style>
    body{
        background-image: url(http://pictures.std-1056.ist.mospolytech.ru/blackfon.jpg)
    }

    .myNews{
        border: 1px solid black;
        padding: 25px;
		background-image: url(http://pictures.std-1056.ist.mospolytech.ru/whitefon.jpg)
    }

    h3{
        color:  rgba(135, 75,160)
    }

    form > button{
		background-color: Transparent;
		background-repeat:no-repeat;
		border: none;
		cursor:pointer;
		overflow: hidden;
		margin-top: 6px;
		
	}

    .date{
        color:  rgba(135, 75,160);
        font-size: 16px;
    }

    .create{
        background-color:  rgba(135, 75,160);
        color: white;
    }
	
</style>
@endsection

src/resources/views/pages/updateNews.blade.php
@extends('layouts.app1')

@section('title')
	Обновление новости
@endsection

@section('content')
	<div class = "container" style = "min-height: 700px; margin-top: 100px">
        <div class="card text-dark bg-light mt-5" style = "width: 75%; margin: 0 auto">
            @include('common.errors')

            <div class="card-header">
                <h3 class = "text-center"> Обновление новости </h3>
            </div>

            <div class="card-body">
                <form action="{{ route('news.update', $currNews->id) }}" method="POST" class="form-horizontal mt-3">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}

                    <div class = "row">
                        <div class = "col-12">
                            <b> Название: </b> 
        
                            <input type = "text" value="{{ $currNews->label }}" name = "label" class = "form-control">
                        </div>

                        <div class = "col-12 mt-2">
                            <b> Изображение: </b>
        
                            <input type = "text" value="{{ $currNews->img }}" name = "img" class = "form-control">
                        </div>
                    </div>

                    <div class = "row mt-2">
                        <div class = "col">
                            <b> Текст: </b> 
                            <textarea type = "text" name = "text" class = "form-control" style = "max-height: 100px; overflow-y: auto" value="{{ $currNews->text }}">{{ $currNews->text }}</textarea>

                            <button type = "submit" name = "Sub" class = "form-control mt-3 btn update">
                                <i class="fas fa-pencil-alt"></i> Обновить
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
	</div>
	
	<style>
		body{
            background-image: url(http://pictures.std-1056.ist.mospolytech.ru/blackfon.jpg)
        }

        h3{
            color: rgba(135, 75,160);
        }

        .update{
            background-color: rgba(135, 75,160);
            color: white;
        }
	</style>

@endsection

src/resources/views/pages/updateWork.blade.php
@extends('layouts.AppLK')

@section('title')
	Редактирование работы
@endsection

@section('content')
	<div class = "container" style = "min-height: 700px; margin-top: 100px">
			<div class="text-center ml-5 mr-5">
			@include('common.errors')
			<div>
        <div class="card text-dark bg-light mt-5" style = "width: 75%; margin: 0 auto">
            <div class="card-header">
                <h5 class = "text-center title"> Редактирование работы </h5>
            </div>

            <div class="card-body"  id="cardW">

                <form action="{{ route('works.update', $report->id) }}" method="POST" class="form-horizontal mt-3" enctype="multipart/form-data">
                    {{ csrf_field() }}
					{{ method_field('PUT') }}
                    <div class = "row">
						<div class = "col-12">
                            <h5><b> Автор: </b></h5>
							<h5><p> {{ $report->User->surname }}&nbsp;{{ $report->User->name }} </p></h5>
                        </div>
                        <div class = "col-12 mt-2">
                            <h5><b> Тема: </b></h5>
                            <input type = "text" value="{{ $report->topic }}" name = "topic" class = "form-control">
                        </div>

                        <div class = "col-12 mt-2">
                            <h5><b> Название работы: </b></h5>
                            <input type = "text" value="{{ $report->label }}"  name = "label" class = "form-control">
                        </div>
						<div class = "col-12 mt-2">
                            <h5><b> Название работы (English): </b></h5><span class="dop">(необязательно)</span>
                            <input type = "text" name = "label_en" value="{{ $report->label_en }}" class = "form-control">
                        </div>

                        <div class = "col-12 mt-2">
                            <h5><b> Форма участия: </b></h5><span class="dop">(очная, заочная, очно-заочная)</span>  
                            <input type = "text" name = "part_form" value="{{ $report->part_form }}" class = "form-control">
                        </div>

                        <div class = "col-6 mt-2">
                            <h5><b> Ученая степень: </b></h5><span class="dop">(необязательно)</span> 
                            <input type = "text" name = "academic_degree" value="{{ $report->academic_degree }}" class = "form-control">
                        </div>

                        <div class = "col-6 mt-2">
                            <h5><b> Ученое звание: </b></h5><span class="dop">(необязательно)</span>
                            <input type = "text" name = "academic_label" value="{{ $report->academic_label }}" class = "form-control">
                        </div>

                        <div class = "col-12 mt-2">
                            <h5><b> Номер секции: </b></h5>
                             <input type = "text" name = "section_number" value = "{{ $report->section_number }}" class = "form-control">
                        </div>

						<div class = "col-12 mt-2">
                            <h5><b> Соавторы: </b></h5><span class="dop">(необязательно)</span>
                             <input type = "text" name = "collaborator" value = "{{ $report->collaborator }}"  class = "form-control">
                        </div>
						<div class = "col-12 mt-2">
							<h5><b> Документ (загружайте только в формате .docx): </b></h5>
							<input type="file" name="file" value = "{{ $report->file }}" class="form-control mb-3 ">
						</div>
                    </div>
                        <button type = "submit" name = "Sub" value = "Редактировать работу" class = "form-control mt-3 btn update" >
                            <i class="far fa-edit"></i> Редактировать
                        </button>
                </form>
            </div>
        </div>
	</div>
	
	<style>
		body{
        background-image: url(http://pictures.std-1056.ist.mospolytech.ru/blackfon.jpg)
    }

	#cardW{
		background-image: url(http://pictures.std-1056.ist.mospolytech.ru/whitefon.jpg)
	}
	
	.dop{
		font-size: 18px;
	}

    .update{
        background-color:  rgba(135, 75,160);
		color: white;
    }

    .title{
        color:  rgba(135, 75,160);
    }
	</style>

@endsection